### ISSUE TITLE
Update to be compatible with current sentry-raven

### ISSUE THREAD

**Issue by ekohl** [timogoebel/foreman_concrete#2]
The dependency on sentry-raven is here:
https://github.com/timogoebel/foreman_concrete/blob/bed3cc64be993c56656aed4597d8600ca195e117/foreman_concrete.gemspec#L17
Versions 2.x require faraday < 1 but we're updating to 1.x (while 2.x is also out). This limits us in packaging.

It looks like you can easily update to sentry-raven 3.x, which itself is also in maintenance mode. Another option is to move to the current version which has a new main class (`Sentry`).

If you're no longer interested in the plugin we can also drop it from packaging.

**Comment by timogoebel** [comment]
> If you're no longer interested in the plugin we can also drop it from packaging.

@ekohl: We don't use the plugin anymore, so feel free to drop it from packaging.
